export const SELECT_CATEGORY = "SELECT_CATEGORY";
export const SELECT_TYPE_SORT = "SELECT_TYPE_SORT";
export const SELECT_PRICE_RANGE = "SELECT_PRICE_RANGE";
export const SELECT_NAME_SEARCH = "SELECT_NAME_SEARCH";
export const UNSELECT_FILTERS = "UNSELECT_FILTERS";
