export const CREATE_CATEGORY = "CREATE_CATEGORY";
export const SET_CREATE_CATEGORY_IMG = "SET_CREATE_CATEGORY_IMG";
export const SET_CREATE_CATEGORY_NAME = "SET_CREATE_CATEGORY_NAME";
export const DELETE_CATEGORY = "DELETE_CATEGORY";
export const RESET_CATEGORY = "RESET_CATEGORY";
