export const SET_CREATE_PRODUCT_NAME = "SET_CREATE_PRODUCT_NAME";
export const SET_CREATE_PRODUCT_PURCHASE_PRICE =
  "SET_CREATE_PRODUCT_PURCHASE_PRICE";
export const SET_CREATE_SALE_PRICE = "SET_CREATE_SALE_PRICE";
export const SET_CP_STOCK = "SET_CREATE_STOCK";
export const SET_CP_DESCRIPTION = "SET_CREATE_DESCRIPTION";
export const SET_CP_MAIN_IMG = "SET_CREATE_MAIN_IMG";
export const SET_CP_IMGS = "SET_CREATE_IMGS";
export const SET_CP_CATEGORIES = "SET_CREATE_CATEGORIES";
export const SET_CP_SUPPLIERS = "SET_CREATE_SUPPLIERS";
